---
title: "Literature dissection"
subtitle: "Spring 2026"
author: "Alex Gonzales, Ethan Castelazo, and Zelda Reiff"
date: "5/20/2026"
format: 
  pdf:
    toc: true
bibliography: references.bib
csl: ecology.csl
---

# Photo documentation

## Table

| Photo point number | Date of photo | Season | Direction of photo | Link to photo |
|:--------------|:--------------|:--------------|:--------------|:--------------|
| 42 | April 2025 | Spring | South | [here](https://ucsb.app.box.com/s/l1n165rti3jgivcmwjl499px0hsy93jx/file/2055677759503) |
| 42 | October 2024 | Fall | South | [here](https://ucsb.app.box.com/s/l1n165rti3jgivcmwjl499px0hsy93jx/file/1687221407621) |
| 42 | April 2025 | Spring | North East | [here](https://ucsb.app.box.com/s/l1n165rti3jgivcmwjl499px0hsy93jx/file/2055677457084) |
| 42 | October 2024 | Fall | North East | [here](https://ucsb.app.box.com/s/l1n165rti3jgivcmwjl499px0hsy93jx/file/1687228662238) |
| 42 | April 2025 | Spring | South East | [here](https://ucsb.app.box.com/s/l1n165rti3jgivcmwjl499px0hsy93jx/file/2055670082237) |
| 42 | October 2024 | Fall | South East | [here](https://ucsb.app.box.com/s/l1n165rti3jgivcmwjl499px0hsy93jx/file/1687230621022) |


We chose to examine photos from water year 2025, which started on October 1st 2024 and ended on September 30th 2025. Our study is focused on how water elevation's relationship to bird abundance, specifically in water year 2025, so photos from Fall 2024 and Spring 2025 are most relevant. We selected photo point 42, positioned on the Northern end of NCOS along the West Elings Marsh trail, because its photos capture a broad landscape of the slough's profile, and water elevation is easily observable from that perspective.

# Reports or posters

## Report or poster information

Title: Bird Community Analysis Report 1967–2015

Authors: Karen A. Stahlheber

Year published: 2015

Permalink: [here](https://escholarship.org/uc/item/1sg3v19d)

Dataset used (likely): Table 3.3 (Common and abundant species at selected sites in surveys from 1990 to 2014),

Key insights: Single-day and mean abundances of bird species across locations at NCOS from 1990-2014. The species with the highest mean abundances at each site are, for the most part, not within the taxon we are focusing on (shorebirds and waterfowl). However, the single-day abundance data provides us with some valuable metrics to compare our own data to, it provides abundance measurements for a variety of sandpiper species (shorebirds) and geese (waterfowl). Across all species, the waterfowl and shorebird taxons did not display the most abundant species at any location, but just comparing the two taxonomic groups, shorebird species were generally more abundant than waterfowl species.

Relevance to your study (be specific here with the question you have asked, the figures you've made, the insights you've gained, etc.): Our plots are visualizing bird species abundance within the waterfowl and shorebird taxonomic groups at NCOS, in relation to water elevation. We also have subplots that compare species abundance between shorebirds and waterfowl through time. This report provides relevant species abundance information at NCOS, which we can compare to our plots to identify changes and trends through time. It is important to acknowledge that this figure does not include abundance data for every species across every site and only includes data from 1990-2014.

# Annotated bibliography

### Paper 1

Title: "Monitoring waterbird abundance in wetlands: The importance of controlling results for variation in water depth"

Authors: Bolduc, Afton

Main findings (2-4 sentences): In most non-diving waterbirds, abundance can predicted through a non-linear relationship with wetland water elevation [@bolduc2008]. Abundance is low when water depth is 0, increasing as water height increases until a maximum is reached, then declining back to zero when depth becomes too deep to support foraging. After modeling abundance trends of two different hypothetical waterbird species (one generalist species and one specialist species) in four different hypothetical wetland habitats (differing in water height), the researchers found that relatively corrected abundance of the generalist species varied greatly among wetland types, indicating water height has a significant impact on average abundance.

Relevance to study (2-4 sentences): Water elevation at NCOS is highly variable over the course of a given water year, meaning average Waterbird abundance is subject to change based on the hydrologic regime of Devereux Slough, according to the findings of Bolduc and Afton. The author's do mention, however, that Shorebirds are one group that diverges from the trends they plotted. Although they did not expand on this caveat, this was an important detail of their publication in relation to our study, as Shorebirds are one of two groups we're choosing to investigate. We'll need to keep this in mind moving forward.

### Paper 2

Title: "Effects of Water Level Fluctuation on Waterbirds Distribution and Aquatic Vegetation Composition at Natural Wetland Reserve, Peninsular Malaysia"

Authors: Rajpar, Zakaria

Main findings (2-4 sentences): In this study conducted in Peninsular Malaysia, researchers found water level to be a major factor that influences the relative abundance and distribution of ducks [@rajpar2011a], along with many other families of bird that are not relevant to our study. Water elevation directly effects aquatic vegetation composition, which in turn determines the hunting and nesting patterns of waterbirds, therefore water level reflects the status/quality of habitat for waterbirds at a given time.

Relevance to study (2-4 sentences): Although this research was conducted in a distant region whose wetland species composition differs greatly from that of the Devereux Slough, these findings connect the dots between aquatic vegetation, water level, and waterbird abundance. This paper reminds us that we must consider *all* factors that play a role in determining bird abundance, including aquatic vegetation dynamics, when contextualizing our own findings, even though vegetation may not be included in our research questions.

### Paper 3

Title: Enhanced Migratory Waterfowl Distribution Modeling by Inclusion of Depth to Water Table Data

Authors: Kreakie, Fan, Keitt

Main findings (2-4 sentences): By applying a Depth to Water Table (DWT) to waterfowl distribution models, researchers increased modeling accuracy - a significant addition to waterfowl models, as they usually perform at a worse accuracy compared to other bird species distribution models [@kreakie2012]. The authors found that the DWT's ability to predict (a dynamic global dataset at 270m resolution) changes to wetland water levels according to changes in the environment, will allow for more mechanistic predictions of how wetland species will respond.

Relevance to study (2-4 sentences): This publication is centered mostly on modeling techniques and applying remotely sensed data (the DWT) to model waterfowl distribution trends at a national scale, which doesn't align very closely to the methods or goals of our project. That said, this article is still relevant to our research question because it places such high importance on water elevation as a controlling factor in the context of waterfowl abundance. Their results, which showed models that use the DWT report higher accuracy compared to those that don't use it, indicate that water elevation is a significant causal variable that's worth investigating in our study.

### Paper 4

Title: "Effects of water level on waterbird abundance and diversity along the middle section of the Danube River"

Authors: Farago and Katalin

Main findings (2-4 sentences): In this long-term study conducted along an 83 km stretch of the Danube River, researchers found that total waterbird abundance was negatively correlated with water level throughout the water year [@faragó2012]. During flood events, dabbling ducks dispersed to peripheral waters outside the survey area, while diving ducks abandoned the study reach entirely due to reduced foraging efficiency in the intense flood waters. High water levels were also found to eliminate key micro habitats such as gravel banks, shoals, and paved riverbanks, creating conditions broadly unfavorable for most waterbird species.

Relevance to study (2-4 sentences): This paper provides good empirical support for a negative relationship between elevated water levels and waterbird abundance, which is directly relevant to interpreting abundance trends at Devereux Slough as water elevation fluctuates across the water year. The study's distinction between dabbling ducks and diving ducks in their responses to high water is particularly useful for our research, because it highlights that different groups within waterfowl respond to hydrologic change in different ways. We should keep in mind, however, that the Danube is a large, fast-flowing river system whose hydrology differs significantly from the shallow, tidally influenced conditions of NCOS, so the mechanisms driving abundance declines may not translate directly to our study site.

### Paper 5

Title: eBird Data Highlight Shifts in Wetland Resources Structuring Waterfowl and Shorebird Abundance

Authors: Donnelly, Patrick

Main findings (2-4 sentences): In this study, researchers determined that gradual losses in wetland land area in the western U.S. due to increasing drought conditions correlate to lower bird species abundance as measured through shorebird and waterfowl species (@donnelly2026). For many wetland dependent species, often species that migrate to these areas for reproduction, measured wetland loss (19-48% loss in the past 20 years) and predicted wetland area loss in the near future will show significant decreases in waterfowl and shorebird species.

Relevance to study (2-4 sentences): Although our project is focused on bird abundance at NCOS, a designated wetland conservation area, insights about the correlation between wetlands and bird species abundance add important context about abundance levels possible in healthy wetland ecosystems to the abundance data we present. These insights provide valuable ecological insights to our own data, emphasizing the importance of the conservation efforts at NCOS.

### Paper 6

Title: Quantifying shorebird habitat in managed wetlands by modeling shallow water depth dynamics

Authors: Schaffer-Smith, Danica

Main findings (2-4 sentences): Scientists can measure water depth with satellite imagery and high-resolution topography to determine the most suitable water depth ranges and broader habitat availability (@schaffer-smith2018). In this study, scientists found that moderate water depths (not extremely shallow or deep) had the highest habitat potential for shorebird species and even asserted that strategic maintenance of water levels could increase habitat suitability for birds.

Relevance to study (2-4 sentences): We are plotting species abundance on waterfowl and shorebird species in relation to water elevation. This report provides important insights into possible abundance patterns due to differences in water elevation; we may expect higher species abundance in the mid-range of water elevation as opposed to the shallower or deeper elevations.

### Paper 7

Title: Waterbird Communities in Managed Wetlands of Varying Water Depth

Authors: Colwell, M.A.

Main findings (2-4 sentences): In this study, scientists found a strong correlation between bird abundance and water depth, specifically that to promote the greatest species abundance and density, managed wetlands should flood to about 10-20 cm for variable depths that support a variety of species. This is mainly due to the fact that wading birds and waterfowl have the ecological niche of shallower water while other driving species are better suited to deeper water.

Relevance to study (2-4 sentences): Since we are focusing on waterfowl and shorebird species, we can consider the conclusion that shallower water elevations support greater species abundance across all measured species. We can compare this metric to our own data to better articulate possible contributors to trends in abundance.

\*Could not find DOI for this report

Colwell, M. A., & O. W. Taft. (2000). Waterbird Communities in Managed Wetlands of Varying Water Depth. *Waterbirds: The International Journal of Waterbird Biology*, *23*(1), 45–55. http://www.jstor.org/stable/4641109\*

### Paper 8

Title: Habitat quality and drought effects on breeding mallard and other waterfowl populations in California, USA

Authors: Kahara, Sharon

Main findings (2-4 sentences): California supports up to 500,000 waterfowl individuals in the spring and summer months, but reduced precipitation and melting snowpacks have contributed to decreased water elevations and a general reduction in wetland breeding habitats (@kahara2021). Contributors to this study proposed that habitat reduction that leads to overcrowding may also have negative effects on populations like disease and resource depletion.

Relevance to study (2-4 sentences): This report provides seasonal data (spring and summer) on waterfowl abundance that we can consider when analyzing our own species abundance data. In other words, we may expect higher waterfowl species abundance in the spring and summer months. However, abundance may also be influenced by other ecological factors that differ from this specific report including land area, vegetation cover, etc.

### Paper 9

Title: Trends in abundance of wintering waterbirds relative to rainfall patterns at a central California estuary, 1972–2015

Authors: Stenzel, Page

Main findings (2-4 sentences): In this 2 period study on waterbird abundance patterns at Bolinas Lagoon located in Central California, researchers found a negative relationship between precipitation and waterbird abundance (@stenzel2017). Flooded ricefields and restored wetlands located in inland Central California, both of which are more prominent with high rainfall, caused coastal waterbirds to migrate more inland than stay at Bolinas Lagoon. 22 taxa used flooded ricefields as an alternative habitat with 12 out of the 22 taxa consistently shifting to ricefields when they flood, this suggests that local Bolinas waterbird distribution is linked to increased inland ricefield flooding.

Relevance to study (2-4 sentences): While our study examines the relationship between water elevation and waterfowl abundance, rainfall patterns are strictly tied to water elevation. Therefore, if water elevation increases and waterfowl abundance decreases, this doesn’t automatically correlate with local conditions not being good enough, but it could mean that other habitats inland have been established.

### Paper 10

Title: Modeling the Relationship between Water Level, Wild Rice Abundance, and Waterfowl Abundance at a Central North American Wetland

Authors: Kevin Aagaard, Josh Eash, Walt Ford, Patricia J. Heglund, Michelle McDowell & Wayne E. Thogmartin

Main findings (2-4 sentences): This study took place at the Rice Lake Nation Wildlife Refuge in east Minnesota in the years 1990-2012 observing correlation between wild rice abundance and waterfowl from Spring to Fall (@aagaard2018). In this survey, no significant evidence was found that the wild rice was increasing waterfowl abundance in the refuge because wild rice is only a portion of the waterfowl diet, and this survey did not take place during peak wild rice growing season. Water elevation however, is directly correlated with wild rice abundance.

Relevance to study (2-4 sentences): Since waterfowl abundance was not influenced by wild rice abundance from Spring-Fall, this provides evidence that any decline of waterfowl in NCOS isn’t attributed to the abundance of wild rice at in-land habitats. However, since wild rice growth is directly linked to water elevation, this effect can be more pronounced in the winter season when rainfall occurs often.

### Paper 11

Title: Interspecific Differences in Habitat Use of Shorebirds and Waterfowl Foraging in Managed Wetlands of California's San Joaquin Valley

Authors: Isola, C.R., Colwell, M.A., Taft, O.W., and Safran, R.J.

Main findings (2-4 sentences): This study found that there is high variability between shorebirds and waterfowl with preferred water elevations. Sandpipers prefer 1–1.3 cm, within 10 m of the water's edge. Dunlin, Dowitchers, Black-necked Stilt, and the American Avocet prefer 3–9.5 cm, roughly 15–20 m from the edge. Green-winged teal prefers 13 cm, about 33 m from the edge. And finally the Northern Shoveler, Northern Pintail, and Gadwall prefer 22–25 cm, more than 45 m from the edge.

Relevance to study (2-4 sentences): Water elevation is our studied variable between waterfowl and shorebirds, since both taxonomic groups exhibit different preferences of water elevation, this highlights variability between their response to water elevation. Waterfowl may especially be sensitive to low water elevation periods because they prefer higher water elevations than shorebirds.

*Could not find DOI for this report

<https://www.jstor.org/stable/4641140?seq=1>

### Paper 12

Title: Monitoring Species Richness and Abundance of Shorebirds in the Western Great Basin

Authors: Nils Warnock, Susan M. Haig

Main findings (2-4 sentences): Although year to year variability of shorebird counts were extreme when observed in wetlands of the Western Great Basin, the general consensus from this study is that different shorebird species prefer different water elevations (@warnock1998). However, these preferences are strict because of the length of the species’ bill and legs. Additionally, the study found that both ground surveys and aerial surveys alone are insufficient: ground surveys capture species diversity while being unable to estimate population size while aerial surveys provide the opposite information.

Relevance to study (2-4 sentences): The data of NCOS bird counts itself may be skewed if ground and aerial surveys were not taken in tandem, just as this Great Basin survey found. Additionally, this study provides further evidence that shorebirds are sensitive to different water elevations, with some species utilizing shallower depths than others, therefore exemplifying the sensitivity of shorebird abundance to water elevation.

# References
